language: node_js
node_js:
- stable
before_install:
- npm install -g npm
script:
- npm install
- npm run test
#deploy:
#  provider: heroku
#  api_key:
#    secure: JLR9F0IonGBeYZB9ypMD1GT1zswdGtTsJQ71bWXlwOCxGvL7Ak7oUGtbVeRHqIh1rSaVVf3WXuGOTDfGGM35j8Lzyph3fBm2gPQWyrFtvdpjIZkxQIRaR0fYdjrqkx1Qzpt60/XhhpyQPfpOFoSEcO32sOT/Dgtix7mSTKvSK+JwbId9WkgoEs01gWh0brnpP8l1EGEu/kvT3U+2Gy0TfLxisNU5u+156kcWcNk5JTgnkWM5GqPQ7mVGU7IUWZocCxAIRxmJXBWaPMcaN68a8jj5vXH4YthMxr5ceS7+//J1RgTP84UMJThlJb+7C4OtgRHFQfL3mYqlOnCjMyrePvuKImflkEI3eQtoD2S2ushFgRk8ox/3XGiKLzM7TA3puPrlO+YkFjoap8/T6eRmRY/y86xCUuwza3M+bd1RftZglcZfEXzElp9bXUFOwToPg4U6cHMG2aQwtr38VBxgwcKk07nSYw3Vy1wHoy1tzs+d2eg+mOXTdnT0Ukwk1TTzsPSZjYNymmV8j8vincB/7uiVjyd8HRn48gSs8LXxfmgu5D7HbI8dqcpH9gGZOd20dYewimyzwG7XzuYxoPWdT7/aagx9AepovqdilKlA+4YK5XMWbluGjX0romWJQkmThA4iZgPVja3VQWkbeZ/4CypEkctA6EXRZkjKrns9V5E=
#  app: lb-a
#  on:
#    branch: main
#    node_js: node
#  skip_cleanup: 'true'
